### ISSUE TITLE
heroku_addon_attachment uses app_id instead of app

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/terraform-provider-heroku#93] opened 2018-07-16 06:11 UTC
All the `heroku` resources that depend on `heroku_app` take `app` as a parameter; however, `heroku_addon_attachment` (added in #19) takes `app_id` instead. While this is easy to workaround, it is inconsistent with all the other resources. 

The same is true for the `addon_id` parameter, but probably less of an issue since it's less prevalent.

### Terraform Version
v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- `heroku_addon_attachment`

### Terraform Configuration Files
See below for relevent snippets

### Expected Behavior
Something like this should work:

```
resource "heroku_addon_attachment" "addons_kafka_01" {
  addon = "${heroku_addon.kafka_01.id}"
  app = "${heroku_app.addons_app.name}"
  name = "KAFKA_01"
}
```

### Actual Behavior
Instead, you have to do this:

```
resource "heroku_addon_attachment" "addons_kafka_01" {
  addon_id = "${heroku_addon.test.id}"
  app_id = "${heroku_app.addons_app.name}"
  name = "TEST_01"
}
```

### Steps to Reproduce
n/a

### Important Factoids
n/a

### References
#19 cc: @JamesBelchamber

**Comment by JamesBelchamber** [comment] 2018-07-16 10:39
The inconsistency is caused by what's available on the API - it's not actually possible to refer to the name of the app or the addon when creating the attachment, only the UUID. Check [the docs](https://godoc.org/github.com/cyberdelia/heroku-go/v3#AddOnAttachment) for details.

**Comment by JamesBelchamber** [comment] 2018-07-16 14:29
Nice! If this works for both the addon (`heroku_addon.test.name`) and app (`heroku_app.test.name`) then you should go ahead and submit a patch to the code, tests and docs :)

**Comment by ryanbrainard** [comment] 2018-07-16 14:36
@JamesBelchamber Do you know what this will mean for backward compatibility? I'm assuming we'll need to keep the `app_id` and `app_name` around as deprecated/hidden params as to not break existing configurations; however, will there be a path forward for users to upgrade? Can they re-import them or just do a refresh or something? Or would they just be stuck with the old version until they destroy and re-create the resource? I'm pretty new to Terraform, so not sure what's the best way to not break people but also give a path forward.

**Comment by JamesBelchamber** [comment] 2018-07-16 14:44
It'll break things :) I dunno if that's really a problem though. Someone with more authority will review it - personally I'd just break it and let someone tell you to make it backwards compatible (or not).

It won't actually break the state, only their code (people would have to do `app_id > app` and `addon_id > addon`) since the ID and name is interchangeable (and they could carry on using either/or). No re-importing would be necessary :)

**Comment by joestump** [comment] 2018-07-16 16:18
@JamesBelchamber it'll definitely break state. Both `app_id` and `addon_id` are marked as [`ForceNew: true`](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_addon_attachment.go#L24-L34) in the schema. What people _could_ do is update those attributes to use the app/add-on names and it'd "just work". 

@davidji99 created a state migration recently that addresses this somewhat. We could mark the `_id` attributes as `Deprecated` in the schema, add the two new parameters, and let people decide what to do with their resources.

**Comment by JamesBelchamber** [comment] 2018-07-16 16:20
Good point, didn't think of that. TBH with addon attachments it probably doesn't really matter if they're recreated, YMMV though.

**Comment by joestump** [comment] 2018-07-16 16:23
It'd result in at least a little bit of downtime I'd suspect. DB connections would be killed/recreated while the re-attachment happened I suspect (and SaaS integrations would temporarily go offline). 

I think the best approach would be to add the two new fields and use them interchangeably. We can then mark the `_id` attributes as `Deprecated`. This leaves it up to the end-user when, or if, they decide to do an attachment re-add dance.

**Comment by davidji99** [comment] 2018-07-16 19:08
Let's also strive for backwards compatibility as much as possible and give people time to move forward with whatever proposed change comes out of this issue. State migrations will likely help here with some UUID/name swaps.

**Comment by davidji99** [comment] 2018-07-16 19:24
There's also inconsistency in how the value some resources in this provider are storing as the `d.Id` or the resource Id in state. `heroku_app` uses the `name` but `heroku_addon` uses the `UUID`.  I propose that first order of business is to standardize this and make consistent across the board. From there, all `app` attributes could be renamed to `app_id`.

It just seems in this heroku world of two values as primary keys, we need some order and consistency here.

**Comment by ryanbrainard** [comment] 2018-07-17 04:49
> There's also inconsistency in how the value some resources in this provider are storing as the d.Id or the resource Id in state. heroku_app uses the name but heroku_addon uses the UUID. 

Just to be sure I understand where you mean, is this what you're talking about?

https://github.com/terraform-providers/terraform-provider-heroku/blob/735fc12a76e109234fb63fc9707c8e4d7bbe29ec/heroku/resource_heroku_app.go#L265

I did an audit of all the `resource_heroku_*.go` files, and luckily, it's only `heroku_app` that's doing that (all the other are using `.id`), but yes, that seems really bad if someone ever renames their app.

> From there, all app attributes could be renamed to app_id.

That's going to be a *much* bigger change. I took a look at the AWS provider as an example for comparison, but it does seem like `*_id` is used more, but not totally consistent there either. Is there a documented best practice and/or style guide for Terraform providers? I can see that `*_id` would be better, but it also could cause a lot of churn if it's something the project doesn't feel strongly about.

**Comment by joestump** [comment] 2018-07-17 14:51
> Is there a documented best practice and/or style guide for Terraform providers?

@davidji99 and I would pay good money for such a link. The best we've got is a private Slack channel for us maintainers where we can ask questions. They're good at responding, but it's fair to say the docs on how to make a great provider are seriously lacking.

**Comment by davidji99** [comment] 2018-07-17 16:04
Yeah @ryanbrainard, L256 on `terraform-provider-heroku/heroku/resource_heroku_app.go`.

I have been talking with @joestump about using the UUID as the resource id moving forward since that makes more sense in the long run especially after your mention of people can rename app names. We can always do `d.Set("name", resource.Name)` if people want to easily identify resources in the state file. 

My recommendation of app attributes being renamed to `app_id` stems from heroku use of two primary keys. `app` invites people to either do `heroku_app.foobar.id` or `heroku_app.foobar.name` since the underlying platform API doesn't care. However in a lot of cases, the `app` attribute is set to `ForceNew` so using the `.id` or `.name` could cause a destroy/recreate. By using `app_id`, it sends a clear message to use the resource id instead of the name. Thoughts?

As for a style guide, I don't think there is one. I've looked to the AWS provider as documentation and inspiration but that provider isn't always consistent.

**Comment by ryanbrainard** [comment] 2018-07-18 02:02
> My recommendation of app attributes being renamed to app_id stems from heroku use of two primary keys. app invites people to either do heroku_app.foobar.id or heroku_app.foobar.name since the underlying platform API doesn't care. However in a lot of cases, the app attribute is set to ForceNew so using the .id or .name could cause a destroy/recreate. By using app_id, it sends a clear message to use the resource id instead of the name. Thoughts?

Yes, I think that makes sense, especially since app (or space, etc) renames could throw a wrench into things. The `id` (UUID) should be thought of as the primary key and the name as the alternate key. The [API docs](https://devcenter.heroku.com/articles/platform-api-reference#data-integrity) agree with this as well:

> Both unique id and more human-friendly attributes can be used reference resources. For example you can use name or id to refer to an app. Though the human-friendly version may be more convenient, id should be preferred to avoid ambiguity.

If we were to make such a change, would it mean marking all the `app`, etc. attributes as `Deprecated: true`? Then could existing users then re-import to move over to the new `app_id`, etc attributes? Or there doesn't happen to be some kind of concept of versioning for providers?

Should open a new issue for planning and tracking this work?

**Comment by davidji99** [comment] 2018-07-18 18:40
We might be able to write a migration for this but I'm not sure just yet.

Since this is a big change, I'd like additional feedback: @joestump @bernerdschaefer @talbright Thoughts on standardizing on `app_id` for downstream resources that require the app resource?

**Comment by talbright** [comment] 2018-09-14 12:53
To answer your question @davidji99...

Given the feedback here and comments by @mars in #124, it's starting to sound more and more compelling to make this change.

The blast radius could be significant though, I'm hoping we can minimize that. I don't like the idea of this change requiring all users to re-import resources. 😢 So the first order of business should be figuring that out.

**Comment by davidji99** [comment] 2018-09-17 22:16
> I'm hoping we can minimize that. I don't like the idea of this change requiring all users to re-import resources.

We'll need write a bunch of migrations to move existing state from the app name to app_id.

Then we should discuss changing the attribute of `app` and other upstream resources to `*_id` to make it clear the resource wants the UUID not the name.

Finally, as new resources are implemented, we should review and recommend using `app_id` or `addon_id` if these new resources require a parent resource.

**Comment by mars** [comment] 2022-02-03 01:08
I just opened a [fresh draft PR](https://github.com/heroku/terraform-provider-heroku/pull/332) 🍃 to fix this by changing all resources to use app IDs. It's a breaking, major-version changeset that would finally fix a variety of these `id` 🆚 `name` problems by standardizing this provider to app ID.

Would love to hear perspectives of how to move this forward on that PR 🙏

**Closed** 2022-02-15 15:44 UTC
